BaiTap07/BaiTap07/Models/ErrorViewModel.cs
namespace BaiTap07.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

BaiTap07/BaiTap07/Models/TheLoai.cs
using System.ComponentModel.DataAnnotations;

namespace BaiTap07.Models
{
	public class TheLoai
	{
		[Key]
		public int Id { get; set; }
		[Required(ErrorMessage ="Không được để rỗng tên thể loại!")]
		[Display(Name="Thể loại")]
		public string Name { get; set; }
        [Required(ErrorMessage = "Không đúng định dạng ngày tháng năm!")]
		[Display(Name="Ngày tạo")]
        public DateTime DateCreated { get; set; } = DateTime.Now;
	}
}

BaiTap07/BaiTap07/Controllers/HomeController.cs
using BaiTap07.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BaiTap07.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

BaiTap07/BaiTap07/Controllers/TheLoaiController.cs
using BaiTap07.Data;
using BaiTap07.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BaiTap07.Controllers
{
    public class TheLoaiController : Controller
    {
        private readonly ApplicationDbContext _db;
        public TheLoaiController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var theloai = _db.TheLoai.ToList();
            var theloai = _db.TheLoai.Where(t => t.Id > 3 || t.DateCreated < new DateTime(2022, 2, 22)).ToList();
            ViewBag.theloai = theloai;
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TheLoai theloai)
        {
            if (ModelState.IsValid)
            {
                _db.TheLoai.Add(theloai);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var theloai = _db.TheLoai.Find(id);

            return View(theloai);
        }
        [HttpPost]
        public IActionResult Edit(TheLoai theloai)
        {
            if (ModelState.IsValid)
            {
                _db.TheLoai.Update(theloai);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var theloai = _db.TheLoai.Find(id);

            return View(theloai);
        }
        [HttpGet]
        public IActionResult Details (int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var theloai = _db.TheLoai.Find(id);

            return View(theloai);
        }
        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            var theloai = _db.TheLoai.Find(id);
            if (theloai == null)
            {
                return NotFound();
            }
            _db.TheLoai.Remove(theloai);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BaiTap07/BaiTap07/Views/TheLoai/Details.cshtml
@model TheLoai
<div class="container">
    <h3>Xem chi tiết thể loại</h3>
    <form method="post" asp-action="Details">
    
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name">Tên Thể Loại</label>
            <input asp-for="Name" type="text" class="form-control" readonly/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DateCreated">Ngày Tạo</label>
            <input asp-for="DateCreated" type="date" class="form-control" readonly/>
            <span asp-validation-for="DateCreated" class="text-danger"></span>
        </div>
     
        <a asp-action="Index" class="btn btn-secondary">Quay lại</a>


    </form>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BaiTap07/BaiTap07/Views/TheLoai/Index.cshtml
<div class="container">
    <h3>Tìm kiếm:</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Tên Thể Loại</th>
                <th>Ngày Tạo</th>
                <th>Chức năng</th>
            </tr>
        </thead>
    
            @foreach(var item in @ViewBag.theloai)
            {
                <tbody>
                <tr>
                    <td width="30%">@item.Name</td>
                    <td width="30%">@string.Format("{0:dd/MM/yyyy}",item.DateCreated)</td>
                    <td width="40%">
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> -
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> -
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>           
                    </td>
                </tr>
                </tbody>
            }
 
    </table>
    <a asp-controller="TheLoai" asp-action="Create" class="btn btn-primary">Thêm mới</a>
</div>